[[keymaps]]
command = "VolumeUp"
key_sequence = "0"
[[keymaps]]
command = "VolumeDown"
key_sequence = "9"
[[keymaps]]
command = "Mute"
key_sequence = "m"
[[keymaps]]
command = "NextTrack"
key_sequence = "K"
[[keymaps]]
command = "PreviousTrack"
key_sequence = "J"
[[keymaps]]
command = "PreviousPage"
key_sequence = "q"
[[keymaps]]
command = "LyricPage"
key_sequence = "y"
[[keymaps]]
command = "FocusNextWindow"
key_sequence = "l"
[[keymaps]]
command = "FocusPreviousWindow"
key_sequence = "h"
[[keymaps]]
command = "ResumePause"
key_sequence = "p"
[[keymaps]]
command = "Quit"
key_sequence = "C-q"
[[keymaps]]
command = "LibraryPage"
key_sequence = "g h"
