creation_rules:
  - path_regex: secrets/(archisteamfarm|authelia|automations|backup|ddclient|hermes|ieb|jellyfin|matriz|nix|proxy|rclone|wg)\.sops\.yaml
    age: >-
      age19wxpznth9v4qc46lzzvall6xmazexykkz59ax6w0n4nrgpkcrassld7n3v,
      age1jsdf5x72y30aq0ghpuwyn9nv6w7m2jgh3f309kpqaf0jw0d4mgrscefqfp,
      age1x7qu0en7rg0qm6rq5dfvyn3w34se2qt6wdw7yzgtwjkgj3skssgqmeut5m,
      age1mjx26v4arpyvr0d433av50cc96qrjmjvzxsxq5rp627eu59vld6seak96h
