import type { Plugin } from "@opencode-ai/plugin"

const ALL: Record<string, { name: string }> = {
  "global.amazon.nova-2-lite-v1:0": { name: "global.amazon.nova-2-lite-v1:0" },
  "global.anthropic.claude-fable-5": { name: "global.anthropic.claude-fable-5" },
  "global.anthropic.claude-haiku-4-5-20251001-v1:0": { name: "global.anthropic.claude-haiku-4-5-20251001-v1:0" },
  "global.anthropic.claude-opus-4-5-20251101-v1:0": { name: "global.anthropic.claude-opus-4-5-20251101-v1:0" },
  "global.anthropic.claude-opus-4-6-v1": { name: "global.anthropic.claude-opus-4-6-v1" },
  "global.anthropic.claude-opus-4-7": { name: "global.anthropic.claude-opus-4-7" },
  "global.anthropic.claude-opus-4-8": { name: "global.anthropic.claude-opus-4-8" },
  "global.anthropic.claude-opus-5": { name: "global.anthropic.claude-opus-5" },
  "global.anthropic.claude-sonnet-4-20250514-v1:0": { name: "global.anthropic.claude-sonnet-4-20250514-v1:0" },
  "global.anthropic.claude-sonnet-4-5-20250929-v1:0": { name: "global.anthropic.claude-sonnet-4-5-20250929-v1:0" },
  "global.anthropic.claude-sonnet-4-6": { name: "global.anthropic.claude-sonnet-4-6" },
  "global.anthropic.claude-sonnet-5": { name: "global.anthropic.claude-sonnet-5" },
  "global.cohere.embed-v4:0": { name: "global.cohere.embed-v4:0" },
  "global.openai.gpt-5.6-luna": { name: "global.openai.gpt-5.6-luna" },
  "global.openai.gpt-5.6-sol": { name: "global.openai.gpt-5.6-sol" },
  "global.openai.gpt-5.6-terra": { name: "global.openai.gpt-5.6-terra" },
  "global.twelvelabs.pegasus-1-2-v1:0": { name: "global.twelvelabs.pegasus-1-2-v1:0" },
  "global.xai.grok-4.6": { name: "global.xai.grok-4.6" },
  "us.amazon.nova-2-lite-v1:0": { name: "us.amazon.nova-2-lite-v1:0" },
  "us.amazon.nova-lite-v1:0": { name: "us.amazon.nova-lite-v1:0" },
  "us.amazon.nova-micro-v1:0": { name: "us.amazon.nova-micro-v1:0" },
  "us.amazon.nova-premier-v1:0": { name: "us.amazon.nova-premier-v1:0" },
  "us.amazon.nova-pro-v1:0": { name: "us.amazon.nova-pro-v1:0" },
  "us.anthropic.claude-3-haiku-20240307-v1:0": { name: "us.anthropic.claude-3-haiku-20240307-v1:0" },
  "us.anthropic.claude-3-sonnet-20240229-v1:0": { name: "us.anthropic.claude-3-sonnet-20240229-v1:0" },
  "us.anthropic.claude-fable-5": { name: "us.anthropic.claude-fable-5" },
  "us.anthropic.claude-haiku-4-5-20251001-v1:0": { name: "us.anthropic.claude-haiku-4-5-20251001-v1:0" },
  "us.anthropic.claude-opus-4-1-20250805-v1:0": { name: "us.anthropic.claude-opus-4-1-20250805-v1:0" },
  "us.anthropic.claude-opus-4-5-20251101-v1:0": { name: "us.anthropic.claude-opus-4-5-20251101-v1:0" },
  "us.anthropic.claude-opus-4-6-v1": { name: "us.anthropic.claude-opus-4-6-v1" },
  "us.anthropic.claude-opus-4-7": { name: "us.anthropic.claude-opus-4-7" },
  "us.anthropic.claude-opus-4-8": { name: "us.anthropic.claude-opus-4-8" },
  "us.anthropic.claude-opus-5": { name: "us.anthropic.claude-opus-5" },
  "us.anthropic.claude-sonnet-4-20250514-v1:0": { name: "us.anthropic.claude-sonnet-4-20250514-v1:0" },
  "us.anthropic.claude-sonnet-4-5-20250929-v1:0": { name: "us.anthropic.claude-sonnet-4-5-20250929-v1:0" },
  "us.anthropic.claude-sonnet-4-6": { name: "us.anthropic.claude-sonnet-4-6" },
  "us.anthropic.claude-sonnet-5": { name: "us.anthropic.claude-sonnet-5" },
  "us.deepseek.r1-v1:0": { name: "us.deepseek.r1-v1:0" },
  "us.meta.llama3-1-70b-instruct-v1:0": { name: "us.meta.llama3-1-70b-instruct-v1:0" },
  "us.meta.llama3-1-8b-instruct-v1:0": { name: "us.meta.llama3-1-8b-instruct-v1:0" },
  "us.meta.llama3-2-11b-instruct-v1:0": { name: "us.meta.llama3-2-11b-instruct-v1:0" },
  "us.meta.llama3-2-1b-instruct-v1:0": { name: "us.meta.llama3-2-1b-instruct-v1:0" },
  "us.meta.llama3-2-3b-instruct-v1:0": { name: "us.meta.llama3-2-3b-instruct-v1:0" },
  "us.meta.llama3-2-90b-instruct-v1:0": { name: "us.meta.llama3-2-90b-instruct-v1:0" },
  "us.meta.llama3-3-70b-instruct-v1:0": { name: "us.meta.llama3-3-70b-instruct-v1:0" },
  "us.meta.llama4-maverick-17b-instruct-v1:0": { name: "us.meta.llama4-maverick-17b-instruct-v1:0" },
  "us.meta.llama4-scout-17b-instruct-v1:0": { name: "us.meta.llama4-scout-17b-instruct-v1:0" },
  "us.mistral.pixtral-large-2502-v1:0": { name: "us.mistral.pixtral-large-2502-v1:0" },
  "us.openai.gpt-5.6-luna": { name: "us.openai.gpt-5.6-luna" },
  "us.openai.gpt-5.6-sol": { name: "us.openai.gpt-5.6-sol" },
  "us.openai.gpt-5.6-terra": { name: "us.openai.gpt-5.6-terra" },
  "us.writer.palmyra-x4-v1:0": { name: "us.writer.palmyra-x4-v1:0" },
  "us.writer.palmyra-x5-v1:0": { name: "us.writer.palmyra-x5-v1:0" },
  "us.xai.grok-4.6": { name: "us.xai.grok-4.6" },
  "amazon.nova-lite-v1:0": { name: "amazon.nova-lite-v1:0" },
  "amazon.nova-micro-v1:0": { name: "amazon.nova-micro-v1:0" },
  "amazon.nova-pro-v1:0": { name: "amazon.nova-pro-v1:0" },
  "deepseek.v3.2": { name: "deepseek.v3.2" },
  "google.gemma-3-27b-it": { name: "google.gemma-3-27b-it" },
  "google.gemma-3-12b-it": { name: "google.gemma-3-12b-it" },
  "google.gemma-3-4b-it": { name: "google.gemma-3-4b-it" },
  "meta.llama3-70b-instruct-v1:0": { name: "meta.llama3-70b-instruct-v1:0" },
  "meta.llama3-8b-instruct-v1:0": { name: "meta.llama3-8b-instruct-v1:0" },
  "minimax.minimax-m2": { name: "minimax.minimax-m2" },
  "minimax.minimax-m2.1": { name: "minimax.minimax-m2.1" },
  "minimax.minimax-m2.5": { name: "minimax.minimax-m2.5" },
  "mistral.devstral-2-123b": { name: "mistral.devstral-2-123b" },
  "mistral.magistral-small-2509": { name: "mistral.magistral-small-2509" },
  "mistral.ministral-3-14b-instruct": { name: "mistral.ministral-3-14b-instruct" },
  "mistral.ministral-3-3b-instruct": { name: "mistral.ministral-3-3b-instruct" },
  "mistral.ministral-3-8b-instruct": { name: "mistral.ministral-3-8b-instruct" },
  "mistral.mistral-7b-instruct-v0:2": { name: "mistral.mistral-7b-instruct-v0:2" },
  "mistral.mistral-large-2402-v1:0": { name: "mistral.mistral-large-2402-v1:0" },
  "mistral.mistral-large-3-675b-instruct": { name: "mistral.mistral-large-3-675b-instruct" },
  "mistral.mistral-small-2402-v1:0": { name: "mistral.mistral-small-2402-v1:0" },
  "mistral.mixtral-8x7b-instruct-v0:1": { name: "mistral.mixtral-8x7b-instruct-v0:1" },
  "mistral.voxtral-mini-3b-2507": { name: "mistral.voxtral-mini-3b-2507" },
  "mistral.voxtral-small-24b-2507": { name: "mistral.voxtral-small-24b-2507" },
  "moonshotai.kimi-k2.5": { name: "moonshotai.kimi-k2.5" },
  "moonshot.kimi-k2-thinking": { name: "moonshot.kimi-k2-thinking" },
  "nvidia.nemotron-nano-12b-v2": { name: "nvidia.nemotron-nano-12b-v2" },
  "nvidia.nemotron-nano-3-30b": { name: "nvidia.nemotron-nano-3-30b" },
  "nvidia.nemotron-nano-9b-v2": { name: "nvidia.nemotron-nano-9b-v2" },
  "nvidia.nemotron-super-3-120b": { name: "nvidia.nemotron-super-3-120b" },
  "openai.gpt-oss-120b-1:0": { name: "openai.gpt-oss-120b-1:0" },
  "openai.gpt-oss-20b-1:0": { name: "openai.gpt-oss-20b-1:0" },
  "openai.gpt-oss-safeguard-120b": { name: "openai.gpt-oss-safeguard-120b" },
  "openai.gpt-oss-safeguard-20b": { name: "openai.gpt-oss-safeguard-20b" },
  "qwen.qwen3-32b-v1:0": { name: "qwen.qwen3-32b-v1:0" },
  "qwen.qwen3-coder-30b-a3b-v1:0": { name: "qwen.qwen3-coder-30b-a3b-v1:0" },
  "qwen.qwen3-coder-next": { name: "qwen.qwen3-coder-next" },
  "qwen.qwen3-next-80b-a3b": { name: "qwen.qwen3-next-80b-a3b" },
  "qwen.qwen3-vl-235b-a22b": { name: "qwen.qwen3-vl-235b-a22b" },
  "writer.palmyra-vision-7b": { name: "writer.palmyra-vision-7b" },
  "zai.glm-4.7": { name: "zai.glm-4.7" },
  "zai.glm-4.7-flash": { name: "zai.glm-4.7-flash" },
  "zai.glm-5": { name: "zai.glm-5" },
}

export default (async () => ({
  config: async (cfg: any) => {
    // Inject every available Bedrock model (us. + global. + bare on-demand).
    // The native provider only surfaces us. profiles; this adds the rest.
    const p = (cfg.provider ??= {})["amazon-bedrock"] ??= {}
    p.name ??= "Amazon Bedrock"
    p.npm ??= "@ai-sdk/amazon-bedrock"
    p.models = Object.assign({}, p.models, ALL)
  },
})) satisfies Plugin
