#!/usr/bin/env bash

#if bluetoothctl info "$device" | grep 'Connected: yes' -q; then
#  bluetoothctl disconnect "$device"
#else
#  bluetoothctl connect "$device"
#fi

if [ -n "$(bluetoothctl devices Connected)" ]; then
  bluetoothctl disconnect
else
  bluetoothctl connect "$device"
fi
