#!/bin/sh
while :; do
mpc current | sed 's|^[^/ ]*/||g' | sed 's|([^)]*)||g' | sed 's/\[[^]]*\]//g' | sed 's/[ ]*\.[a-z0-9]*$//g' | tee ~/.local/share/currentsong
mpc current --wait >/dev/null
wait;
done &!
