# symlink in /etc/docker/compose/dlsuite/docker-compose.yaml
version: '3.4'
networks:
    default:
        name: dlsuite
        external: true

x-environment: &default-tz-puid-pgid
  TZ: America/Argentina/Buenos_Aires
  PUID: 1001
  PGID: 963

services:
    prowlarr:
        image: 'lscr.io/linuxserver/prowlarr:latest'
        container_name: prowlarr
        environment: *default-tz-puid-pgid
        volumes:
            - '/home/docker/prowlarr:/config:Z'
        ports:
            - '9696:9696'
        restart: unless-stopped
#    flaresolverr:
#        image: 'ghcr.io/flaresolverr/flaresolverr:latest'
#        container_name: flaresolverr
#        environment:
#          - LOG_LEVEL=${LOG_LEVEL:-info}
#          - LOG_HTML=${LOG_HTML:-false}
#          - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
#          - TZ=America/Argentina/Buenos_Aires
#        ports:
#          - '8191:8191'
#        restart: unless-stopped
    qbittorrent:
        container_name: qbittorrent
        environment: *default-tz-puid-pgid
        volumes:
            - '/home/docker/qbittorrent:/config:Z'
            - '/home/docker/data/torrents:/data/torrents:z'
        ports:
            - '54536:54536'
            - '8080:8080'
        restart: unless-stopped
        image: 'ghcr.io/hotio/qbittorrent:latest'
    sonarr:
        container_name: sonarr
        environment: *default-tz-puid-pgid
        volumes:
            - '/dev/rtc:/dev/rtc:ro'
            - '/home/docker/sonarr:/config:Z'
            - '/home/docker/data:/data:z'
        ports:
            - '8989:8989'
        links:
            - qbittorrent
        restart: unless-stopped
        image: 'lscr.io/linuxserver/sonarr:latest'
    radarr:
        container_name: radarr
        environment: *default-tz-puid-pgid
        volumes:
            - '/home/docker/radarr:/config:Z'
            - '/home/docker/data/:/data:z'
        ports:
            - '7878:7878'
        links:
            - qbittorrent
        restart: unless-stopped
        image: 'lscr.io/linuxserver/radarr:latest'
    bazarr:
        image: 'lscr.io/linuxserver/bazarr:latest'
        container_name: bazarr
        environment: *default-tz-puid-pgid
        volumes:
            - '/home/docker/bazarr:/config:Z'
            - '/home/docker/data:/data:z'
        ports:
            - '6767:6767'
        restart: unless-stopped
    jellyfin:
        image: 'lscr.io/linuxserver/jellyfin:latest'
        container_name: jellyfin
        environment:
            - PUID=974
            - PGID=971
            - TZ=America/Argentina/Buenos_Aires
            - JELLYFIN_PublishedServerUrl=jellyfin.repparw.com.ar
            - DOCKER_MODS=linuxserver/mods:jellyfin-amd
        devices:
            - '/dev/dri:/dev/dri'
        volumes:
            - '/home/docker/jellyfin:/config:Z'
            - '/home/docker/data/media:/data/media:ro'
        ports:
            - '8096:8096'
            - '8920:8920' #optional
            - '7359:7359/udp' #optional
        restart: 'unless-stopped'
    freshrss:
        image: 'lscr.io/linuxserver/freshrss:latest'
        container_name: freshrss
        environment: *default-tz-puid-pgid
        volumes:
            - '/home/docker/freshrss:/config:Z'
        ports:
            - '81:80'
        restart: unless-stopped
    mercury:
        image: wangqiru/mercury-parser-api:latest
        container_name: mercury
        ports:
          - 3000:3000
        restart: unless-stopped
    grocy:
        image: lscr.io/linuxserver/grocy:latest
        container_name: grocy
        environment: *default-tz-puid-pgid
        volumes:
          - '/home/docker/grocy:/config:Z'
        ports:
          - 9283:80
        restart: unless-stopped
    swag:
        image: 'lscr.io/linuxserver/swag:latest'
        container_name: swag
        cap_add:
            - NET_ADMIN
        environment:
            - DOCKER_MODS=linuxserver/mods:universal-cron
            - TZ=America/Argentina/Buenos_Aires
            - PUID=1001
            - PGID=963
            - URL=repparw.com.ar
            - SUBDOMAINS=wildcard
            - VALIDATION=dns
            - DNSPLUGIN=cloudflare 
        volumes:
            - '/home/docker/swag:/config:Z'
        ports:
            - '443:443'
            - '80:80'
        restart: unless-stopped
