# symlink in /etc/docker/compose/dlsuite/docker-compose.yaml
version: '3.3'
networks:
    default:
        name: dlsuite
        external: true
services:
    prowlarr:
        image: 'linuxserver/prowlarr:latest'
        container_name: prowlarr
        environment:
            - PUID=1001
            - PGID=963
            - TZ=America/Argentina/Buenos_Aires
        volumes:
            - '/home/docker/prowlarr:/config:Z'
        ports:
            - '9696:9696'
        restart: unless-stopped
    qbittorrent:
        container_name: qbittorrent
        environment:
            - PUID=1001
            - PGID=963
        volumes:
            - '/home/docker/qbittorrent:/config:Z'
            - '/home/docker/data/torrents:/data/torrents:z'
        ports:
            - '54536:54536'
            - '8080:8080'
        restart: unless-stopped
        image: 'linuxserver/qbittorrent:latest'
    sonarr:
        container_name: sonarr
        environment:
            - PUID=1001
            - PGID=963
            - TZ=America/Argentina/Buenos_Aires
        volumes:
            - '/dev/rtc:/dev/rtc:ro'
            - '/home/docker/sonarr:/config:Z'
            - '/home/docker/data:/data:z'
        ports:
            - '8989:8989'
        links:
            - qbittorrent
        restart: unless-stopped
        image: 'linuxserver/sonarr:latest'
    radarr:
        container_name: radarr
        environment:
            - PUID=1001
            - PGID=963
            - TZ=America/Argentina/Buenos_Aires
        volumes:
            - '/home/docker/radarr:/config:Z'
            - '/home/docker/data/:/data:z'
        ports:
            - '7878:7878'
        links:
            - qbittorrent
        restart: unless-stopped
        image: 'linuxserver/radarr:latest'
    bazarr:
        image: 'linuxserver/bazarr:latest'
        container_name: bazarr
        environment:
            - PUID=1001
            - PGID=963
            - TZ=America/Argentina/Buenos_Aires
        volumes:
            - '/home/docker/bazarr:/config:Z'
            - '/home/docker/data:/data:z'
        ports:
            - '6767:6767'
        restart: unless-stopped
    jellyfin:
        image: 'linuxserver/jellyfin:latest'
        container_name: jellyfin
        environment:
            - PUID=974
            - PGID=971
            - TZ=America/Argentina/Buenos_Aires
            - JELLYFIN_PublishedServerUrl=jellyfin.repparw.com.ar
            - DOCKER_MODS=linuxserver/mods:jellyfin-amd
        devices:
            - '/dev/dri:/dev/dri'
        volumes:
            - '/home/docker/jellyfin:/config:Z'
            - '/home/docker/data/media:/data/media:ro'
            - '/run/media/repparw/HDD:/data/hdd:ro'
        ports:
            - '8096:8096'
            - '8920:8920' #optional
            - '7359:7359/udp' #optional
        restart: 'unless-stopped'
    freshrss:
        image: 'linuxserver/freshrss:latest'
        container_name: freshrss
        environment:
            - PUID=1001
            - PGID=963
            - TZ=America/Argentina/Buenos_Aires
        volumes:
          - '/home/docker/freshrss:/config:Z'
        ports:
            - '81:80'
        restart: unless-stopped
    swag:
        image: 'linuxserver/swag:latest'
        container_name: swag
        cap_add:
            - NET_ADMIN
        environment:
            - PUID=1001
            - PGID=963
            - TZ=America/Argentina/Buenos_Aires
            - URL=repparw.com.ar
            - SUBDOMAINS=wildcard
            - VALIDATION=dns
            - DNSPLUGIN=cloudflare 
        volumes:
            - '/home/docker/swag:/config:Z'
        ports:
            - '443:443'
            - '80:80'
        restart: unless-stopped
