#!/bin/sh
rsync -aq ~/.config/zsh ~/.config/scripts ~/.config/systemd ~/.config/kitty ~/.config/mpv ~/.config/tmux ~/.config/spotifyd ~/.config/spotify-player ~/.config/wireplumber ~/.config/lf/ ~/.config/zathura/ ~/.config/nvim ~/.config/feh ~/.config/k-backup ~/git/desktopconfig 
cd ~/git/desktopconfig; git add .; git commit -am "Auto-Commit"; git push
