#!/bin/sh
rsync -aq ~/.zshrc ~/.zsh_aliases ~/.zprofile ~/.zsh_history ~/.config/scripts ~/.config/kitty ~/.config/mpd ~/.config/mpv ~/.config/lf/ ~/.config/zathura/ ~/.config/nvim ~/.config/feh ~/.config/k-backup ~/git/desktopconfig 
cd ~/git/desktopconfig; git add .; git commit -am "Auto-Commit"; git push
