#!/bin/sh

tmux new-session -d -s mine
tmux send-keys 'minexmr' 'C-m'
tmux select-window -t mine:0
tmux split-window -h
tmux send-keys 'temp' 'C-m'
tmux select-pane -t 0
tmux split-window -v 'cd ~/git/chia-blockchain && . ./activate && chia start farmer && sleep 30s && watch -n 43200 chia farm summary'
tmux split-window -h
tmux send-keys 'gputemp' 'C-m'
tmux select-pane -t 0
tmux -2 attach-session -t mine
