#!/bin/sh

tmux new-session -d -s mine
tmux send-keys 'gpumine -i 100' 'C-m'
tmux select-window -t mine:0
tmux split-window -h
tmux send-keys 'sleep 30s; cpumine --cpu-max-threads-hint=85' 'C-m'
tmux split-window -v
tmux send-keys '~/.config/scripts/tmux_watcher&!; temp' 'C-m'
tmux select-pane -t 0
tmux split-window -v 
tmux send-keys 'cd ~/git/chia-blockchain && . ./activate && chia start farmer && sleep 30s; watch -n 43200 chia farm summary' 'C-m'
#tmux split-window -h
#tmux send-keys 'gputemp' 'C-m'
tmux select-pane -t 2
tmux resize-pane -R 15
tmux select-pane -t 0
tmux -2 attach-session -t mine
