#!/bin/sh
while true
do
  sleep 2m
  if ! tmux list-sessions -f mine &> /dev/null; then
	echo TMUX SESSION DROPPED at $(date +"%b %d %R");
	for i in 1 2 3; do paplay /usr/share/sounds/freedesktop/stereo/suspend-error.oga; done
  fi
done

