#!/bin/sh
pkill -f /dev/video0 || mpv --demuxer-lavf-format=video4linux2 --demuxer-lavf-o-set=input_format=mjpeg --profile=low-latency --untimed --geometry=-0-0 --autofit=30% --vf=hflip av://v4l2:/dev/video0
