theme = "gruvbox_dark"
client_id = "2728200c381a418983c3de5b30bc77a9"
client_port = 8080
playback_format = """
{track} • {artists}
{album}
{metadata}"""
tracks_playback_limit = 50
app_refresh_duration_in_ms = 32
playback_refresh_duration_in_ms = 0
page_size_in_rows = 20
play_icon = "▶"
pause_icon = "▌▌"
liked_icon = "♥"
border_type = "Plain"
progress_bar_type = "Rectangle"
playback_window_position = "Top"
cover_img_length = 9
cover_img_width = 5
cover_img_scale = 1.0
playback_window_width = 6
enable_streaming = "Always"
enable_cover_image_cache = true
default_device = "spotifyd"

[copy_command]
command = "wl-copy"
args = []

[device]
name = "Terminal UI"
device_type = "computer"
volume = 40
bitrate = 320
audio_cache = false
normalization = false
