[[keymaps]]
command = "VolumeUp"
key_sequence = "0"
[[keymaps]]
command = "VolumeDown"
key_sequence = "9"
[[keymaps]]
command = "Mute"
key_sequence = "m"
[[keymaps]]
command = "NextTrack"
key_sequence = "n"
[[keymaps]]
command = "PreviousTrack"
key_sequence = "b"
[[keymaps]]
command = "PreviousTrack"
key_sequence = "p"
[[keymaps]]
command = "PreviousPage"
key_sequence = "q"
[[keymaps]]
command = "FocusNextWindow"
key_sequence = "l"
[[keymaps]]
command = "FocusPreviousWindow"
key_sequence = "h"
[[keymaps]]
command = "Quit"
key_sequence = "C-q"
[[keymaps]]
command = "LibraryPage"
key_sequence = "g h"
[[keymaps]]
command = "LyricPage"
key_sequence = "g l"

# === #

[[actions]]
action = "CopyLink"
key_sequence = "y"
target = "PlayingTrack"

[[actions]]
action = "CopyLink"
key_sequence = "Y"

[[actions]]
action = "GoToArtist"
key_sequence = "g A"
target = "PlayingTrack"
[[actions]]
action = "GoToAlbum"
key_sequence = "g B"
target = "PlayingTrack"
[[actions]]
action="ToggleLiked"
key_sequence="C-l"
target = "PlayingTrack"
