discordWebhook: ENC[AES256_GCM,data:aH1EfaJJd8ojIfhKle0aCJboov2n4ENxHlL49kbviKkjMsPH3mcs0UBQiBbP3Ki5PPzxUUgN07yCu+BXIxBamRfDEwjXUgjQJ3gMEHQkJL+eV0L95aVTchSoSHeSJMai2+KatwpZDvbg22GspAw6F8SXHYhK0rq8Eg==,iv:e/8U/hq2Vu1wf6E/hdaN30BUu9Jvs6uM2YatsnvZf3c=,tag:ilVZKM0a0DOQLynlqQ5lfA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArR1VUcDdseGFOSCtnNDNY
            YWhNY1M1Wm8vQ2xVUnBtUDZxWmNIazJIQ3o0ClZRRWRpYXJQM1NtZ2lkRzNCeHNC
            T1krdWc1OGpyZE00dnZFa3ZaaTg4cmcKLS0tIFBJd0ovcXRNaHJ0dWkyZUhRZ0Mz
            SGhsek53NVg2bGl1dG02c0VvbS82aVkKNKgLnnDIhV1acEUFmB5aChrytW96K5Nj
            z64dx5cB+DysBaSKuPirHok/pSjbrjaQmM4zeHB7DYCgxXlCl6YpgA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19wxpznth9v4qc46lzzvall6xmazexykkz59ax6w0n4nrgpkcrassld7n3v
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBURjFabFhIend1TU82dmx5
            VVFtaDVCWG90VFo0a3lWcjVtRGhQSVZzR1drCitydmtlcEV5UmFsQ3p0YnpTTWND
            dEhCTkZMM2s1NHZSakdxOVBrY292cnMKLS0tIHBPM0pUUVFZWXJ5aW1xUW4vUGpq
            WFNZaC9HMFBhVzVGOXhsVUFHWmpMWmsKNywswT49ojC5D+5BVNfNxMoF00b7jOcp
            igITNORJ+ITjCDsq0g5GhUFlQl8RJMFRULuVGh4ea+6mDrS4B2K2sA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jsdf5x72y30aq0ghpuwyn9nv6w7m2jgh3f309kpqaf0jw0d4mgrscefqfp
    lastmodified: "2026-07-12T21:11:51Z"
    mac: ENC[AES256_GCM,data:qMSyl+/J8SeXCz6xdoyTend8Ya0bRt0OkQVEyzJcCO8AkPNuCcKhyLB3X336J/bXoorjX32oFPdbYZ67qtvOkq6/f5l48PsfkjlNzK2ACC3s0RnCdpdnEboGbZgF6MaeZHFm+xXP8SjLqdot2F2ns5ZzZFTnFAlNADatsOpihdM=,iv:O9QDtCxchHR3jiD8kUc+8AiZ3Jvb4Yoc7AfKy+tYjhA=,tag:APbBU+bY4wrS/IXrs2JD7A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
